# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

In [4]:
import numpy as np

a = np.arange(10,90,10)
a.reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 2. 다음 행렬과 같은 행렬이 있다.

In [6]:
m = np.arange(0,15,1).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
m[1][2],m[-1][-1]

(7, 14)

In [40]:
m[1][1:3] 

array([6, 7])

In [43]:
m[1:,[2]].reshape(1,-1)

array([[ 7, 12]])

In [46]:
m[1:-1]

array([[5, 6, 7, 8, 9]])

In [50]:
m[0][-2:],m[1][-2:]

(array([3, 4]), array([8, 9]))

# 3번

In [83]:
m1 = np.concatenate(m)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
m = m.flatten().tolist()

In [62]:
m,m1

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [87]:


# [m1[i] for i in range(len(m1)) if m1[i] % 3 == 0]
m1[np.logical_and(m1 % 3==0 , m1 != 0)]
# [ m1[i] for i in range(len(m1)) if m1[i] % 4 == 1 or m[i] % 3 == 0]
m1[np.logical_and(m1 % 4==1 , m1 != 0)]
m1[np.logical_and(m1 % 4==1 , m1 % 3 == 0)]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

# 4번

In [107]:
c = 2 * np.identity(5) + np.eye(5,5,1) + 3* np.eye(5,5,-1)
c


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

# 5번

In [141]:
import random as rd
d =np.random.uniform(0,10,30).reshape(5,6)
d.sum() # 전체의 최대값
for i in range(5):
    print(d[[i],:].sum()) # 각 행의 합
    print(d[[i],:].max())
for i in range(6):
    print(d[:,[i]].sum())
    print(d[:,[i]].min())


24.59759833695427
9.38874514341169
32.53867898690758
9.259969469203588
31.365927946997285
8.698492295037575
27.213381092300533
8.25454237384565
24.001260759403603
7.413331306842182
11.051702418548299
0.5844515193092115
24.677465597852674
2.2350241447210584
20.049750676847232
0.13037653599574983
23.619390878620553
1.5398324009227515
39.27781138823637
4.663028637668784
21.040726162458146
1.2760637973454858


# 6번

In [174]:
e = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71], [ 81, 59, 90, 100]])
f = e.tolist()
h = f[0][:]
f[0][:] = f[1][:]
f[1][:] = h

np.array(f)


array([[ 46,  99, 100,  71],
       [  1,   2,   3,   4],
       [ 81,  59,  90, 100]])

# 7번 

In [178]:
import random
a = np.random.randint(1,6,100)
np.average(a)


2.99

# 8번

In [187]:
b = (np.random.uniform(-1,1,250) / 100) * 10000 + 10000


array([10074.92227095, 10037.07181479, 10040.24957958,  9921.08941584,
       10026.22619763,  9903.99277786,  9989.91357646, 10060.61883566,
       10062.25671488,  9915.11989902, 10091.36101675,  9978.95924951,
        9901.48137974,  9934.23594225,  9997.53969868, 10042.67099387,
       10071.21997881, 10028.22098783, 10014.51510701,  9953.0715572 ,
        9908.27702181, 10026.56909004,  9914.92002879,  9930.62908014,
        9964.05148507, 10018.44456485,  9902.17199378,  9910.56766669,
       10051.60330309,  9995.24212526, 10056.57983773,  9938.01080418,
       10081.03240202, 10092.33183092, 10066.18427343,  9902.67815844,
       10041.45381929,  9978.01576325, 10037.85076529,  9961.48105999,
        9955.07104563,  9925.99040499, 10099.49887978,  9985.11706585,
       10010.71085772, 10001.06687362,  9940.13318038,  9931.13189402,
       10077.8875276 ,  9914.88654062,  9976.01140735, 10055.83380896,
        9935.16161474, 10002.77867594, 10024.10749479,  9943.12945235,
      

In [3]:
import numpy as np
b = (np.random.normal(-1,1,250) / 100) * 10000 + 10000
b


array([10065.65942791,  9989.88676471,  9829.70166996,  9794.66323007,
        9836.89294883,  9920.95752449, 10017.90077613,  9982.03746989,
       10033.05484938,  9868.91165752,  9865.56451349,  9861.09628407,
        9923.56470379,  9865.88710622,  9940.81649453,  9882.24330651,
        9938.74944548, 10137.04104045,  9772.18932825,  9965.87166897,
        9797.65799504, 10007.36563463, 10020.34632594,  9810.89095765,
        9857.04653821, 10012.72176953,  9706.15281794,  9891.41058509,
        9755.71008233,  9833.62577692, 10067.84542591,  9942.63028132,
        9946.01088131, 10037.31096279,  9786.48675275,  9883.94744112,
        9759.9538871 ,  9881.72374346,  9871.40846947,  9903.88026735,
        9817.89875876,  9904.21472221,  9878.16253264,  9958.51356225,
        9884.46614556,  9849.96263388,  9989.49080617,  9759.47961525,
        9954.3682249 ,  9846.45951368,  9895.71601256,  9842.42317409,
       10133.27259041,  9941.41866208, 10085.35597647,  9846.60028101,
      