# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

In [6]:
import numpy as np

a = np.arange(10,90,10).reshape(2,4)
# a = np.arange(1,9).reshape(2,4)*10 한줄에쓰는법 


# 2. 다음 행렬과 같은 행렬이 있다.

In [4]:
m = np.arange(0,15,1).reshape(3,5)

In [ ]:
m[1][2],m[-1][-1]

In [5]:
m[1][1:3]  # 양쪽이 슬라이스면 2차원 한쪽이 인덱스면 값이 하나가 나온다. 유의할것

array([6, 7])

In [8]:
m[1:,[2]].reshape(1,-1)

array([[ 7, 12]])

In [7]:
m[1:-1]

array([[5, 6, 7, 8, 9]])

In [9]:
# m[0][-2:],m[1][-2:]
# m[:-1, 3:] << 좀 더 정답에 가까움 

array([[3, 4],
       [8, 9]])

# 3번

In [10]:
m = np.arange(0,15,1).reshape(3,5)
m1 = m.flatten()
# [m1[i] for i in range(len(m1)) if m1[i] % 3 == 0]
m1[(m1 % 3==0)]
# [ m1[i] for i in range(len(m1)) if m1[i] % 4 == 1 or m[i] % 3 == 0]
m1[(m1 % 4==1)]
m1[np.logical_and(m1 % 4==1 , m1 % 3 == 0)]

array([9])

# 4번

In [15]:
c = 2 * np.identity(5,int) + np.eye(5,5,1,int) + 3* np.eye(5,5,-1,int) # 데이터 타입 정수타입으로줘야함
c

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

# 5번

In [45]:
import random as rd
np.random.seed(2021)
d =np.random.uniform(0,10,30).reshape(5,6).round(4)
print(d.max()) # 전체의 최대값
# axis = 1 행일때 
for i in range(5):
    print(f'{d[[i],:].sum():.4f}') # 각 행의 합
    print(d[[i],:].max())
for i in range(6):
    print(d[:,[i]].sum())
    print(d[:,[i]].min())


9.9724
29.1637
9.9724
25.3385
7.8431
38.0722
9.6384
23.6387
5.743
32.0221
8.231
29.053700000000003
1.7899
29.503300000000003
3.7116
18.576999999999998
0.8663
26.832
2.0185
30.121900000000004
0.9689
14.147300000000001
0.5857


# 6번

In [39]:
e = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71], [ 81, 59, 90, 100]])
f = e.tolist()
h = f[0][:]
f[0][:] = f[1][:]
f[1][:] = h

np.array(f)

# 영어 성적을 argsort()
indices = np.argsort(e[1])  # 매트릭스는 행 데이터 프레임은 열이 기본 
indices
# 내림차순
indices[::-1]
e[: , indices[::-1]]


array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [42]:
# 모든 행을 영어성적 내림차순 기준으로 정
e[:,np.argsort(e[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

# 7번 

In [53]:
import random
np.random.seed(2021)
a = np.random.randint(1,7,100) # 7포함 7포함아님 
# np.average(a)
np.mean(a)



array([1, 2, 3, 4, 5, 6])

In [54]:
# dice array에서의 고유값
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [55]:
# dice array에서의 고유값 및 그개수 
np.unique(a, return_counts=True) # 몇이 몇개 나왔는지 알려주는 함수... 

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [57]:
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

# 8번

In [61]:
# b = (np.random.uniform(-1,1,250) / 100) * 10000 + 10000 # 
 


In [ ]:
# 5개 테스트
import random
np.random.seed(2021)
rate = np.random.normal(0,0.01,250) # 평균이 0이고 표준편차가 0.01 인거 5개
price = 10000
price_list = []
for i in range(250):
    price = np.round(price * (1 + rate[i])) 
    price_list.append(int(price))
price_list

In [76]:
import numpy as np
b = (np.random.normal(-1,1,250) / 100) * 10000 + 10000


In [77]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01,250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)
price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]    

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [79]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01,250)
price = 10000
price_array = np.empty(250,dtype=np.int32)  # 빈어레이를 미리 만들어서 하는방법

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price 
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])