# Numpy Part-1

In [5]:
import numpy as np # 가장 기본으로 쓰는 코드


### 1.Numpy 배열(N-Dimensional Array)

In [6]:
a = np.array([1,3,4,7],float)
a 

array([1., 3., 4., 7.])

In [7]:
a.dtype, a.shape, a.ndim, a.size # dtype 플로트, # a.shape(튜플), a.ndim(1차원 엘리먼트 4개), a.size (나의 사이즈는 몇개?\)

(dtype('float64'), (4,), 1, 4)

In [8]:
# Vector(1차원)
a = np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [9]:
# Matrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [ ]:
b.dtype, b.shape, b.ndim , b.size

In [10]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
c.dtype, c.shape, c.ndim , c.size ## 더블클릭 컨트롤 +d 눌러서 같이 바꾸면 짱편함 

(dtype('int32'), (2, 3, 4), 3, 24)

In [11]:
# dtype
np.array([1,2,3,4],dtype=np.uint8)  ## int와 uint 의 차이점 Ui UNSignd 메모리에 인섹할정도없음

array([1, 2, 3, 4], dtype=uint8)

In [12]:
# reshape # 사이즈만 같으면 reshape 을 얼마든지 할수이싿 . 
c.size

24

In [13]:
c.reshape(3,-1) # -1 니가 알아서 결정해주세요. 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
# c.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
type(c.shape)


tuple

In [35]:
type(c.shape)

tuple

In [30]:
len(c)

24

In [26]:
c.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
a.reshape(4,-1)

array([[1.],
       [3.],
       [4.],
       [7.]])

In [28]:
# reshape을쓰는 이유는 데이터 인식하는게 벡터냐 매트릭스냐 텐서냐에 따라서 달라진다 그에 맞게 배열을 바꿔줘야한다.
# 아이리스를 예로 들면 데이터를 변환해서 줌

In [29]:
a.reshape(-1,4)

array([[1., 3., 4., 7.]])

In [32]:
b.reshape(-1,) # 튜플이라서 

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [33]:
b.flatten() # 1차원으로 변경 다리미로 다리미질 보여주고 싶으면 

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing 

In [37]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a[1][1],a[1,1],a[-1,-2] # [,] numpy에서는 허용을한다. 

(5, 5, 5)

In [41]:
a[1,0:2] # 점심시간때 한번봐 

array([4, 5])

In [44]:
a[:][1:],a[:,1:]

(array([[4, 5, 6]]),
 array([[2, 3],
        [5, 6]]))

In [45]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [48]:
b[0:2,1:]

array([[2, 4],
       [3, 9]])

In [49]:
b[1:,:2]

array([[4, 3],
       [3, 7]])

In [52]:
b[0:2,::2]

array([[1, 4],
       [4, 9]])

### 3. 배열 생성

In [53]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [58]:
np.arange(1,4.1,0.5) # 실수도 지원함 

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [32]:
l = np.arange(1,4.1,0.5).tolist() # tolsit()가 뭘까
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [62]:
np.arange(-2, 2.01,0.02).size # size 체크 201개 

201

In [1]:
# linear space
np.linspace(2,2,201).size

NameError: name 'np' is not defined

In [4]:
np.ones(shape=(10,), dtype=np.int16) # 우리가 만든 어떤 사이즈를 1로 채워라

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros(4) 

array([0., 0., 0., 0.])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.empty(4) # empty 는 기억장소를 만들어 놓는거기 때문에 0이 안나올수도 있다. 

array([0., 0., 0., 0.])

- 대각선: identity, eye

In [12]:
np.identity(3,dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [13]:
# 정방형(n x n)


In [14]:
# 직사각형 indentity (n*m)
np.eye(N=3,M=5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [16]:
np.eye(3, 5, k=1,dtype=np.int8)  

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

- 데이터 분포에 따른 rnadom sampling

In [28]:
np.random.seed(2021)

In [21]:
np.random.random(4)

array([0.99724328, 0.12816238, 0.17899311, 0.75292543])

# 정규분포 

In [22]:
# 종모양 그래프 
# 인위적인게 아닌 자연현상

In [23]:
np.random.normal(10,4 ,4)

array([14.52343305, 12.58000735, 10.42565497, 11.68861932])

In [25]:
# 표준 정규분포
np.random.randn(4) # np.random.normal(0,1,4)

array([-1.90772239,  1.1002243 , -1.40232506, -0.22508127])

In [29]:
# 균등(Uniform) 분포
np.random.uniform(3,4,4)

array([3.60597828, 3.73336936, 3.13894716, 3.31267308])

In [30]:
#p(1-p) 이항분포 binominal 
# 가설검정 두개의 집단을 검정할때 t분포 
# 입각하여 뽑아주는걸 넘파이의 랜덤이라고 한다.
# 어떠한 분포특성에 맞게 뽑아주는걸 
# 확률과통계팩토리얼!   