# Numpy -part2

In [1]:
import numpy as np

### 4.Operation

In [4]:
a = np.arange(1,13).reshape(3,4) ## 그냥 ㄷㅊ고 외워~ 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.sum(axis=0) # 행을 바꾸면서 더해라
a.sum(axis=1) # 열을 바꾸면서 더해라 

array([10, 26, 42])

In [11]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [12]:
np.sort(b) # axis = 1가 디폴트 값이고 행을 정렬한거임 

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [14]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [15]:
np.sort(b, axis=0) # 행 기준으로 정렬 

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [21]:
# 내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42,38,12,25])
np.sort(c)[::-1] # 내림차순 

array([42, 38, 25, 12])

In [22]:
np.argsort(c) # 인덱스값을 출력한것 


array([2, 3, 1, 0], dtype=int64)

In [23]:
indices = np.argsort(c) # arg가 붙으면 인덱스라고 생각하면 마음이 편하다. 
c[indices]

array([12, 25, 38, 42])

In [24]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

-

In [25]:
def sigmoid(x): # 없으면 함수를 만들어서 써야한다. ai할때씀 
    return 1. / (1+np.exp(-x)) # sigmoid 함수는 알아야한다 ai를 해야되기때문에 

In [27]:
xs = np.array([-10,0,10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose

In [28]:
b.T # 행과 열을 바꿔치키함, 전치행렬 

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [32]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
a, b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [34]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [40]:
a - a # 사칙연산도 다된다.

array([[0, 0],
       [0, 0]])

In [41]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [45]:
a ** a 

array([[  1,   4],
       [ 27, 256]], dtype=int32)

- broadcasting

In [46]:
a + 3 

array([[4, 5],
       [6, 7]])

In [48]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [49]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [50]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

# 5. Comparison
### 비교연산

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.any(+a>5)

True

In [54]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [56]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [1]:
np.argmax(a) , np.argmin(a)


NameError: name 'np' is not defined

###  6. Boolean & Fancy

In [59]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [60]:
a[b] # 불리언 인덱스 

array([4, 5, 6])

In [61]:
a[np.logical_or(a < 3 , a > 7)] # 로지칼 오퍼레이션 ~ 

array([0, 1, 2, 8, 9])

In [62]:
a[a > 5]  # 가장 많이쓰는 형태이다 너무너무 편해보인다 . 

array([6, 7, 8, 9])

In [65]:
a[[3,5,7,3]]  # 중복해서든지 가져올수도있다. !   

array([3, 5, 7, 3])

### 기술 통계

In [67]:
a = np.random.randn(10)
a

array([ 2.02138892, -0.11258615, -0.53237095,  0.89619164, -0.60664735,
       -0.88524117, -0.55389904, -0.30163455,  0.58270248,  0.42088918])

In [70]:
# 평균(Mean)
a.mean() , np.mean(a)

(0.09287930166392674, 0.09287930166392674)

In [71]:
# 표준 편차(Standard deviation)
a.std() , np.std(a)

(0.8464721979473269, 0.8464721979473269)

In [72]:
a.max(), a.min()

(2.021388922290245, -0.885241170787458)

In [73]:
# 4분위수 
# 쿼타일?~
# 이상치 outlier ~ 거짓말 하는놈 ㅋ

In [74]:
np.percentile(a,0) # 최소값

-0.885241170787458

In [77]:
np.percentile(a,0),np.percentile(a,25) , np.percentile(a,75) , np.percentile(a,100) 

(-0.885241170787458,
 -0.5485170199925958,
 0.5422491551024009,
 2.021388922290245)

In [78]:
np.percentile(a,0) , a.min()

(-0.885241170787458, -0.885241170787458)

In [80]:
np.percentile(a,50) , np.median(a)

(-0.20711034554873187, -0.20711034554873187)

In [81]:
np.percentile(a,100) , a.max()

(2.021388922290245, 2.021388922290245)

In [82]:
# 집단의 크기
b = np.random.randn(1000)
c = np.random.randn(100000)

In [83]:
#생략# b.mean() , c.mean()
#생략 # b.std(),c.std()

(0.0016248469397022154, 0.0019848655845657814)

In [ ]:
ㅇ