# Numpy 복습 및 연습하기

In [1]:
import numpy as np

In [2]:
array_1 = np.arange(9).reshape(3,3) * 10;
array_1

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [3]:
array_2 = np.arange(9).reshape(3,3) * 10
array_2

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

# Q2.Indexing,Slicing

In [4]:
m = np.arange(15).reshape(3,5) # aragne 의 속성 넘파이 의 특징 이렇게 계산 가능 
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a = (f'{m[0][0]} {m[2][2]} {m[2,2]}')
a.split() # 이거 자체가 리스트 임 


['0', '12', '12']

In [6]:
m1=m[0:,[0]]
m1

array([[ 0],
       [ 5],
       [10]])

In [7]:
m1=m[0:,0]
m1

array([ 0,  5, 10])

In [8]:
type(m1)

numpy.ndarray

In [9]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
# 불린 인덱스 

f = m.flatten() # 2차원을 1차원으로 쭉 펴줌 
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
f[f % 3 ==0] # 불린타입으로 원하는 f를 출력시켜줌 

array([ 0,  3,  6,  9, 12])

In [12]:
f[f % 4 ==1]

array([ 1,  5,  9, 13])

In [13]:
f[np.logical_and(f%3==0,f%4==1)]

array([9])

In [14]:
f[np.logical_or(f%3==0,f%4==1)]

array([ 0,  1,  3,  5,  6,  9, 12, 13])

In [26]:
np.eye(5,5,1,int)+np.eye(5,5,0,int)*2+np.eye(5,5,-1,int)

array([[2, 1, 0, 0, 0],
       [1, 2, 1, 0, 0],
       [0, 1, 2, 1, 0],
       [0, 0, 1, 2, 1],
       [0, 0, 0, 1, 2]])

In [27]:
map(int,np.eye(5,5,1)+np.eye(5,5,0)*2+np.eye(5,5,-1))

In [30]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [31]:
m.max(
    
)

9.9724

In [32]:
m.min()

0.5857

In [37]:
m.sum(axis=0)

array([29.0537, 29.5033, 18.577 , 26.832 , 30.1219, 14.1473])

In [41]:
m.sum()

148.2352

In [39]:
m.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [44]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
a[0][0][0]

0

In [47]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [49]:
indices =np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [53]:
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [56]:
score[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [58]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [59]:
np.mean(dice)

3.7

In [67]:
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [69]:
np.unique(dice,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [70]:
unique , counts = np.unique(dice, return_counts=True)

In [71]:
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [73]:
type(counts)

numpy.ndarray

In [78]:
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250,dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [79]:
import pandas as pd

In [91]:
df = pd.DataFrame(columns=[1,2,3,4,5],index=[1,2,3])

In [99]:
df[6] = np.NaN

In [102]:
df.columns

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [103]:
df.index

Int64Index([1, 2, 3], dtype='int64')